# Generated by Django 2.1.7 on 2019-02-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextoDeEleccion', models.CharField(max_length=200)),
                ('Votos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextoDePregunta', models.CharField(max_length=200)),
                ('FechaDePublicacion', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='eleccion',
            name='Pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encuestas.Pregunta'),
        ),
    ]
